"""
changelog_gen.py — Markdown changelog generator.

Pure Python, no AI calls. Takes category summaries and metadata,
produces structured GitHub-flavored Markdown.
"""

from datetime import date
from typing import Optional

DISPLAY_ORDER = ["feature", "bugfix", "refactor", "documentation", "test", "chore"]

CATEGORY_META: dict[str, tuple[str, str]] = {
    "feature":       ("", "Features"),
    "bugfix":        ("", "Bug Fixes"),
    "refactor":      ("♻️", "Refactoring"),
    "documentation": ("", "Documentation"),
    "test":          ("", "Tests"),
    "chore":         ("", "Chores"),
}


def generate_changelog(
    summaries: dict[str, str],
    repo_url: str,
    date_from: Optional[date],
    date_to: Optional[date],
    last_n: Optional[int],
    commit_count: int,
    output_language: str = "English",
) -> str:
    """Generate a structured Markdown changelog from category summaries."""
    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append("# Changelog\n")

    repo_name = repo_url.rstrip("/").split("github.com/")[-1] if "github.com/" in repo_url else repo_url
    lines.append(f"**Repository:** [{repo_name}]({repo_url})  ")

    if last_n:
        period_str = f"Last {commit_count} commits"
    elif date_from and date_to:
        period_str = f"{date_from} → {date_to}"
    elif date_from:
        period_str = f"Since {date_from}"
    elif date_to:
        period_str = f"Until {date_to}"
    else:
        period_str = "All commits"

    lines.append(f"**Period:** {period_str}  ")
    lines.append(f"**Commits analyzed:** {commit_count}  ")
    lines.append(f"**Output language:** {output_language}  ")
    lines.append("")

    if not summaries:
        lines.append("*No changes found for the selected period.*")
        return "\n".join(lines)

    lines.append("---\n")

    # ── Sections ──────────────────────────────────────────────────────────────
    for category in DISPLAY_ORDER:
        if category not in summaries:
            continue
        emoji, title = CATEGORY_META.get(category, ("", category.title()))
        heading = f"## {emoji} {title}" if emoji else f"## {title}"
        lines.append(heading)
        lines.append("")
        lines.append(summaries[category])
        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("*Generated by [Smart Changelog Generator](https://github.com)*")

    return "\n".join(lines)
