"""
changelog_gen.py — Markdown-Changelog-Generator
Nimmt die von summarizer.py generierten Kategoriezusammenfassungen und Metadaten entgegen und 
erstellt daraus ein strukturiertes Markdown-Dokument.
"""

from datetime import date
from typing import Optional

# Reihenfolge der Kateogien im generierten Changelog
DISPLAY_ORDER = ["feature", "bugfix", "refactor", "documentation", "test", "chore"]

# Mapping von internen Kategorien zu (Emoji, Überschrift) für die Markdown-Ausgabe
CATEGORY_META: dict[str, tuple[str, str]] = {
    "feature":       ("", "Features"),
    "bugfix":        ("", "Bug Fixes"),
    "refactor":      ("♻️", "Refactoring"),
    "documentation": ("", "Documentation"),
    "test":          ("", "Tests"),
    "chore":         ("", "Chores"),
}



def generate_changelog(
    summaries: dict[str, str], repo_url: str,  date_from: Optional[date],  date_to: Optional[date], 
    last_n: Optional[int],  commit_count: int,  output_language: str = "English", ) -> str:
    """
    Erzeugt ein strukturiertes Markdown-Changelog aus den Kategoriezusammenfassungen und Metadaten.
    
    Args:
        summaries:       Dict mit Kategorie → Zusammenfassung (nur vorhandene Kategorien)
        repo_url:        Vollständige GitHub-URL des Repositories
        date_from:       Startdatum des analysierten Zeitraums (optional)
        date_to:         Enddatum des analysierten Zeitraums (optional)
        last_n:          Anzahl der letzten Commits, die analysiert wurden (optional)
        commit_count:    Anzahl tatsächlich verarbeiteter Commits (kann < last_n sein)
        output_language: Sprache des Outputs (wird nur im Header angezeigt,
                         die Übersetzung selbst übernimmt der Summarizer)
    """

    lines: list[str] = []

    # Header 
    lines.append("# Changelog\n")

    # Repository-Namen aus der URL extrahieren (z.B. "pallets/flask") und als Link formatieren
    repo_name = repo_url.rstrip("/").split("github.com/")[-1] if "github.com/" in repo_url else repo_url
    lines.append(f"**Repository:** [{repo_name}]({repo_url})  ")

    # Zeitraum und Anzahl der Commits angeben
    # Wenn last_n angegeben ist, hat das Vorrang vor den Datumsangaben, da es eine genauere Angabe der analysierten Commits ermöglicht.
    if last_n:
        period_str = f"Last {commit_count} commits"
    elif date_from and date_to:
        period_str = f"{date_from} → {date_to}"
    elif date_from:
        period_str = f"Since {date_from}"
    elif date_to:
        period_str = f"Until {date_to}"
    else:
        period_str = "All commits"

    lines.append(f"**Period:** {period_str}  ")
    lines.append(f"**Commits analyzed:** {commit_count}  ")
    lines.append(f"**Output language:** {output_language}  ")
    lines.append("")

    # Frühzeitiger Abbruch, wenn keine Zusammenfassungen vorliegen (z.B. bei leeren Repositories oder wenmn alle Commits gefiltert wurden)
    if not summaries:
        lines.append("*No changes found for the selected period.*")
        return "\n".join(lines)

    lines.append("---\n")

    # Sections 

    # Kategorie in DISPLAY_ORDER durchgehen, damit die Ausgabe immer in der gleichen Reihenfolge erfolgt, 
    # auch wenn summaries nur eine Teilmenge enthält
    for category in DISPLAY_ORDER:
        if category not in summaries:
            continue

        # Emoji und Überschrift für die Kategorie holen, mit Fallback auf den rohen Kategorienamen
        emoji, title = CATEGORY_META.get(category, ("", category.title()))
        heading = f"## {emoji} {title}" if emoji else f"## {title}"
        lines.append(heading)
        lines.append("")
        lines.append(summaries[category]) # LLM-generierte Zusammenfassung für die Kategorie
        lines.append("")

    # Footer 
    lines.append("---")
    lines.append("")
    lines.append("*Generated by Smart Changelog Generator")

    return "\n".join(lines)
